/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

import javax.swing.JPanel;

import co.unicauca.openmarket.client.domain.service.OpenMarketFacadeService;
import co.unicauca.openmarket.client.infra.Messages;
import co.unicauca.openmarket.client.infra.SessionManager;
import co.unicauca.openmarket.commons.domain.User;

/**
 *
 * @author restr
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    private pnlCrearProducto pnlcrearproducto;
    private pnlBajaSuspenderProducto pnlbajasuspenderproducto;
    private pnlBuscarProductos pnlbuscarproductos;
    private pnlComprarProductos pnlcomprarproductos;
    private pnlConfirmarOrden pnlconfirmarorden;
    private pnlPuntuarOrden pnlpuntuarorden;
    private pnlRegistrarEntrega pnlregistrarentrega;
    private pnlCarritoCompras pnlcarritocompras;
    private OpenMarketFacadeService openMarketFacadeService;

    public MainGUI(OpenMarketFacadeService openMarketFacadeService) {
        initComponents();
        initMainGUI();
        this.openMarketFacadeService = openMarketFacadeService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnBuscarProductos = new javax.swing.JButton();
        btnComprarProductos = new javax.swing.JButton();
        btnCarritodeCompras = new javax.swing.JButton();
        btnConfirmarOrdenes = new javax.swing.JButton();
        btnPuntuarOrdenes = new javax.swing.JButton();
        btnCrearEditarProductos = new javax.swing.JButton();
        btnBajaSuspender = new javax.swing.JButton();
        btnRegistrarEntrega = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        txtCorreoUsuario = new javax.swing.JTextField();
        lblCorreoUsuario = new javax.swing.JLabel();
        lblContraseniaUsuario = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnAnonimo = new javax.swing.JButton();
        txtConstraseniaUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenMarket");
        setMinimumSize(new java.awt.Dimension(860, 515));

        pnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlMenu.setMinimumSize(new java.awt.Dimension(140, 515));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 25));

        btnBuscarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProductos.setText("Buscar Productos");
        btnBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBuscarProductos);

        btnComprarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComprarProductos.setText("Comprar Productos");
        btnComprarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarProductosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnComprarProductos);

        btnCarritodeCompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarritodeCompras.setText("Carrito de Compras");
        btnCarritodeCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritodeComprasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCarritodeCompras);

        btnConfirmarOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarOrdenes.setText("Confirmar Ordenes");
        btnConfirmarOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarOrdenesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnConfirmarOrdenes);

        btnPuntuarOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntuarOrdenes.setText("Puntuar Ordenes");
        btnPuntuarOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuarOrdenesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPuntuarOrdenes);

        btnCrearEditarProductos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCrearEditarProductos.setText("Crear/Editar Productos");
        btnCrearEditarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEditarProductosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCrearEditarProductos);

        btnBajaSuspender.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnBajaSuspender.setText("Dar de \nBaja/Suspender");
        btnBajaSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajaSuspenderActionPerformed(evt);
            }
        });
        pnlMenu.add(btnBajaSuspender);

        btnRegistrarEntrega.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarEntrega.setText("Registrar Entrega");
        btnRegistrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEntregaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnRegistrarEntrega);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSalir);

        pnlCentral.setLayout(new java.awt.BorderLayout());

        lblCorreoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreoUsuario.setText("Correo Electronico:");

        lblContraseniaUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseniaUsuario.setText("Contrasenia:");

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        btnAnonimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnonimo.setText("Anonimo");
        btnAnonimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnonimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
                pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addContainerGap(246, Short.MAX_VALUE)
                                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblContraseniaUsuario)
                                                .addComponent(lblCorreoUsuario)
                                                .addComponent(txtCorreoUsuario)
                                                .addComponent(txtConstraseniaUsuario,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                pnlLoginLayout.createSequentialGroup()
                                                        .addComponent(btnIniciarSesion)
                                                        .addGap(32, 32, 32))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                pnlLoginLayout.createSequentialGroup()
                                                        .addComponent(btnAnonimo)
                                                        .addGap(41, 41, 41)))
                                .addContainerGap(284, Short.MAX_VALUE)));
        pnlLoginLayout.setVerticalGroup(
                pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblCorreoUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblContraseniaUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtConstraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(btnIniciarSesion)
                                .addGap(32, 32, 32)
                                .addComponent(btnAnonimo)
                                .addContainerGap(170, Short.MAX_VALUE)));

        pnlCentral.add(pnlLogin, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pnlMainLayout.setVerticalGroup(
                pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMainGUI() {
        setLocationRelativeTo(null);

        btnBuscarProductos.setVisible(false);
        btnCarritodeCompras.setVisible(false);
        btnComprarProductos.setVisible(false);
        btnConfirmarOrdenes.setVisible(false);
        btnCrearEditarProductos.setVisible(false);
        btnPuntuarOrdenes.setVisible(false);
        btnRegistrarEntrega.setVisible(false);
        btnBajaSuspender.setVisible(false);

        this.pnlcrearproducto = new pnlCrearProducto();
        this.pnlbajasuspenderproducto = new pnlBajaSuspenderProducto();
        this.pnlbuscarproductos = new pnlBuscarProductos();
        this.pnlcomprarproductos = new pnlComprarProductos();
        this.pnlconfirmarorden = new pnlConfirmarOrden();
        this.pnlpuntuarorden = new pnlPuntuarOrden();
        this.pnlregistrarentrega = new pnlRegistrarEntrega();
        this.pnlcarritocompras = new pnlCarritoCompras();
    }

    private void cambiarPanel(JPanel jpanel) {
        pnlCentral.removeAll();
        pnlCentral.revalidate();
        pnlCentral.repaint();
        pnlCentral.add(jpanel);
    }

    private void btnBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarProductosActionPerformed
        cambiarPanel(pnlbuscarproductos);
    }// GEN-LAST:event_btnBuscarProductosActionPerformed

    private void btnComprarProductosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComprarProductosActionPerformed
        cambiarPanel(pnlcomprarproductos);
    }// GEN-LAST:event_btnComprarProductosActionPerformed

    private void btnCarritodeComprasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCarritodeComprasActionPerformed
        cambiarPanel(pnlcarritocompras);
    }// GEN-LAST:event_btnCarritodeComprasActionPerformed

    private void btnConfirmarOrdenesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConfirmarOrdenesActionPerformed
        cambiarPanel(pnlconfirmarorden);
    }// GEN-LAST:event_btnConfirmarOrdenesActionPerformed

    private void btnPuntuarOrdenesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPuntuarOrdenesActionPerformed
        cambiarPanel(pnlpuntuarorden);
    }// GEN-LAST:event_btnPuntuarOrdenesActionPerformed

    private void btnCrearEditarProductosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCrearEditarProductosActionPerformed
        cambiarPanel(pnlcrearproducto);
    }// GEN-LAST:event_btnCrearEditarProductosActionPerformed

    private void btnBajaSuspenderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBajaSuspenderActionPerformed
        cambiarPanel(pnlbajasuspenderproducto);
    }// GEN-LAST:event_btnBajaSuspenderActionPerformed

    private void btnRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRegistrarEntregaActionPerformed
        cambiarPanel(pnlregistrarentrega);
    }// GEN-LAST:event_btnRegistrarEntregaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }// GEN-LAST:event_btnSalirActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIniciarSesionActionPerformed
        btnBuscarProductos.setVisible(true);
        btnCarritodeCompras.setVisible(true);
        btnComprarProductos.setVisible(true);
        btnConfirmarOrdenes.setVisible(true);
        btnCrearEditarProductos.setVisible(true);
        btnPuntuarOrdenes.setVisible(true);
        btnRegistrarEntrega.setVisible(true);
        btnBajaSuspender.setVisible(true);
        // 1.Usar el OpenMarket facade service para encontrar el usuario por nombre y
        // contraseña
        String password = txtConstraseniaUsuario.getPassword().toString();
        String email = txtCorreoUsuario.getText();
        User user = null;
        user = openMarketFacadeService.findUserByEmailAndPassword(email, password);
        // 2. Si el usuario no es nulo entonces settear en
        // SessionManager.getInstance().setUsuario(); a ese usuario
        if (user != null) {
            SessionManager.getInstance().setUser(user);
        } else {
            // 2.1 Si es nulo entonces mostrar un mensaje de error y retornar
            Messages.showMessageDialog("Usuario o contraseña incorrectos", "Error");
            return;
        }

        // 3 Luego de las anteriores validaciones dependiendo del tipo de usuario que
        // sea
        // el usuario que se logueo activar los botones correspondientes
        pnlCentral.removeAll();
        pnlCentral.revalidate();
        pnlCentral.repaint();
    }// GEN-LAST:event_btnIniciarSesionActionPerformed

    private void btnAnonimoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAnonimoActionPerformed
        btnBuscarProductos.setVisible(true);

        // Settear un usuaio anonimo en SessionManager.getInstance().setUsuario(); y
        // ocultar los botones que no puede usar
        User anonUser = new User();
        anonUser.setUserName("Anonimo");
        SessionManager.getInstance().setUser(anonUser);
        pnlCentral.removeAll();
        pnlCentral.revalidate();
        pnlCentral.repaint();
    }// GEN-LAST:event_btnAnonimoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnonimo;
    private javax.swing.JButton btnBajaSuspender;
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnCarritodeCompras;
    private javax.swing.JButton btnComprarProductos;
    private javax.swing.JButton btnConfirmarOrdenes;
    private javax.swing.JButton btnCrearEditarProductos;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnPuntuarOrdenes;
    private javax.swing.JButton btnRegistrarEntrega;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblContraseniaUsuario;
    private javax.swing.JLabel lblCorreoUsuario;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPasswordField txtConstraseniaUsuario;
    private javax.swing.JTextField txtCorreoUsuario;
    // End of variables declaration//GEN-END:variables
}
