/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

/**
 *
 * @author restr
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnBuscarProductos = new javax.swing.JButton();
        btnComprarProductos = new javax.swing.JButton();
        btnCarritodeCompras = new javax.swing.JButton();
        btnConfirmarOrdenes = new javax.swing.JButton();
        btnPuntuarOrdenes = new javax.swing.JButton();
        btnCrearEditarProductos = new javax.swing.JButton();
        btnModificarStock = new javax.swing.JButton();
        bntBajaSuspender = new javax.swing.JButton();
        btnRegistrarEntrega = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlCentral = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnAnonimo = new javax.swing.JButton();
        txtConstrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OpenMarket");
        setMinimumSize(new java.awt.Dimension(860, 515));

        pnlMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMenu.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        pnlMenu.setMinimumSize(new java.awt.Dimension(140, 515));
        pnlMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 25));

        btnBuscarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarProductos.setText("Buscar Productos");
        pnlMenu.add(btnBuscarProductos);

        btnComprarProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComprarProductos.setText("Comprar Productos");
        pnlMenu.add(btnComprarProductos);

        btnCarritodeCompras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCarritodeCompras.setText("Carrito de Compras");
        pnlMenu.add(btnCarritodeCompras);

        btnConfirmarOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarOrdenes.setText("Confirmar Ordenes");
        pnlMenu.add(btnConfirmarOrdenes);

        btnPuntuarOrdenes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntuarOrdenes.setText("Puntuar Ordenes");
        pnlMenu.add(btnPuntuarOrdenes);

        btnCrearEditarProductos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnCrearEditarProductos.setText("Crear/Editar Productos");
        pnlMenu.add(btnCrearEditarProductos);

        btnModificarStock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificarStock.setText("Modificar Strock");
        btnModificarStock.setActionCommand("Modificar Stock");
        pnlMenu.add(btnModificarStock);

        bntBajaSuspender.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        bntBajaSuspender.setText("Dar de \nBaja/Suspender");
        pnlMenu.add(bntBajaSuspender);

        btnRegistrarEntrega.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarEntrega.setText("Registrar Entrega");
        pnlMenu.add(btnRegistrarEntrega);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        pnlMenu.add(btnSalir);

        pnlCentral.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Contrasenia:");

        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setActionCommand("Iniciar Sesion");

        btnAnonimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnonimo.setText("Anonimo");

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(txtUsuario)
                        .addComponent(txtConstrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnIniciarSesion)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnAnonimo)
                        .addGap(41, 41, 41)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtConstrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btnIniciarSesion)
                .addGap(32, 32, 32)
                .addComponent(btnAnonimo)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pnlCentral.add(pnlLogin, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBajaSuspender;
    private javax.swing.JButton btnAnonimo;
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnCarritodeCompras;
    private javax.swing.JButton btnComprarProductos;
    private javax.swing.JButton btnConfirmarOrdenes;
    private javax.swing.JButton btnCrearEditarProductos;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnModificarStock;
    private javax.swing.JButton btnPuntuarOrdenes;
    private javax.swing.JButton btnRegistrarEntrega;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlCentral;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPasswordField txtConstrasenia;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
