/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.service.OpenMarketFacadeService;
import co.unicauca.openmarket.client.infra.Messages;
import co.unicauca.openmarket.client.infra.SessionManager;
import co.unicauca.openmarket.commons.domain.Category;
import co.unicauca.openmarket.commons.domain.Product;
import co.unicauca.openmarket.commons.domain.User;
import co.unicauca.openmarket.observer.obs.Observador;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author restr
 */
public class pnlBajaSuspenderProducto extends javax.swing.JPanel implements Observador {

    List<Product> productos;
    /**
     * Creates new form pnlComprador
     */

    private OpenMarketFacadeService OpenMarketFacadeService;

    public pnlBajaSuspenderProducto(OpenMarketFacadeService OpenMarketFacadeService) {
        initComponents();
        initializeTable();
        this.OpenMarketFacadeService = OpenMarketFacadeService;
        User usr = SessionManager.getInstance().getUser();
        if (usr != null) {
            if (!usr.getUserName().equals("Anonimo")) {
                this.productos = OpenMarketFacadeService.getOwnProducts();
                fillTable(productos);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSuspender = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 515));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnSuspender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuspender.setText("Suspender");
        btnSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuspender);

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        this.productos = OpenMarketFacadeService.getOwnProducts();
        fillTable(OpenMarketFacadeService.getOwnProducts());

    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSuspenderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSuspenderActionPerformed
        int selectedIndex = tblProductos.getSelectedRow();
        
        if (selectedIndex < 0) {
            Messages.showMessageDialog("Seleccione un producto de la tabla", "Atenci�n");
            return;
        }
        
        Product product = productos.get(selectedIndex);
        product.getState().setId(2L);
        product.getState().setName("no disponible");
        Category category = new Category();
        category.setId(1L);
        category.setName("Ropa");
        product.setCategory(category);
        OpenMarketFacadeService.updateProduct(product);
        Messages.showMessageDialog("Producto suspendido", "Atenci�n");
    }// GEN-LAST:event_btnSuspenderActionPerformed

    private void initializeTable() {
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Estado", "Nombre", "Descripcion", "Precio", "Stock", "Latitud", "Longitud", "Categoria"
                }));
    }

    private void fillTable(List<Product> listProducts) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();

        Object rowData[] = new Object[8];// No columnas
        for (int i = 0; i < listProducts.size(); i++) {
            rowData[0] = listProducts.get(i).getState().getName();
            rowData[1] = listProducts.get(i).getName();
            rowData[2] = listProducts.get(i).getDescription();
            rowData[3] = listProducts.get(i).getPrice();
            rowData[4] = listProducts.get(i).getStock();
            rowData[5] = listProducts.get(i).getLatitude();
            rowData[6] = listProducts.get(i).getLongitude();
            if (listProducts.get(i).getCategory() != null) {
                rowData[7] = listProducts.get(i).getCategory().getName();
            }

            model.addRow(rowData);
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSuspender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        this.productos = OpenMarketFacadeService.getOwnProducts();
        fillTable(this.productos);
    }

}
