/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.service.OpenMarketFacadeService;
import co.unicauca.openmarket.client.infra.Messages;
import co.unicauca.openmarket.client.infra.SessionManager;
import co.unicauca.openmarket.commons.domain.Product;
import co.unicauca.openmarket.commons.domain.User;
import co.unicauca.openmarket.observer.obs.Observador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author restr
 */
public class pnlComprarProductos extends javax.swing.JPanel implements Observador {

    /**
     * Creates new form pnlComprador
     */
    private OpenMarketFacadeService openMarketFacadeService;
    private List<Product> products;

    public pnlComprarProductos(OpenMarketFacadeService openMarketFacadeService) {
        initComponents();
        initializeTable();
        this.openMarketFacadeService = openMarketFacadeService;

        User usr = SessionManager.getInstance().getUser();
        if (usr != null) {
            if (!usr.getUserName().equals("Anonimo")) {
                this.products = openMarketFacadeService.findAvailableProducts();
                fillTable(products);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnAgrCarrito = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(700, 515));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprar);

        btnAgrCarrito.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgrCarrito.setText("Agregar al Carrito");
        btnAgrCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgrCarrito);

        lblCantidad.setText("Cantidad:");
        jPanel1.add(lblCantidad);

        txtCantidad.setText("1");
        jPanel1.add(txtCantidad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                .createSequentialGroup()
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDescripcion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void initializeTable() {
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "ID", "Nombre", "Descripcion", "Precio", "Stock", "Latitud", "Longitud", "Categoria"
                }));
    }

    private void fillTable(List<Product> listProducts) {
        if (listProducts.isEmpty()) {
            initializeTable();
            return;
        }

        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblProductos.getModel();

        Object rowData[] = new Object[8];// No columnas
        for (int i = 0; i < listProducts.size(); i++) {
            rowData[0] = listProducts.get(i).getId();
            rowData[1] = listProducts.get(i).getName();
            rowData[2] = listProducts.get(i).getDescription();
            rowData[3] = listProducts.get(i).getPrice();
            rowData[4] = listProducts.get(i).getStock();
            rowData[5] = listProducts.get(i).getLatitude();
            rowData[6] = listProducts.get(i).getLongitude();
            rowData[7] = listProducts.get(i).getCategory().getName();

            model.addRow(rowData);
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBuscarActionPerformed
        if (txtNombre.getText().isEmpty() && txtDescripcion.getText().isEmpty()) {
            Messages.showMessageDialog("Debe ingresar el nombre o descripcion del producto a buscar", "Atenci�n");
            txtNombre.requestFocus();
            return;
        }

        products = openMarketFacadeService.findProductByNameAndDescription(txtNombre.getText(),
                txtDescripcion.getText());

        fillTable(products);

    }// GEN-LAST:event_btnBuscarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnComprarActionPerformed
        if (this.products == null) {
            Messages.showMessageDialog("Busque un Producto primero", "Atenci�n");
            return;
        }
        int selectedIndex = tblProductos.getSelectedRow();
        Product product = products.get(selectedIndex);
        if (openMarketFacadeService.buyProduct(product)) {
            Messages.showMessageDialog("Producto comprado", "Atenci�n");
        } else {
            Messages.showMessageDialog("Ocurrio un error", "Atenci�n");
        }
    }// GEN-LAST:event_btnComprarActionPerformed

    private void btnAgrCarritoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgrCarritoActionPerformed
        if (txtCantidad.getText().isEmpty()) {
            Messages.showMessageDialog("Ingrese la cantidad", "Atenci�n");
            return;
        }

        if (!correctFormat(txtCantidad.getText())) {
            Messages.showMessageDialog("Ingrese un dato numerico", "Atenci�n");
            return;
        }
        int selectedIndex = tblProductos.getSelectedRow();
        Product product = products.get(selectedIndex);
        if (openMarketFacadeService.addProductToTheShoppingCart(product,
                Long.parseLong(txtCantidad.getText()))) {
            Messages.showMessageDialog("Producto guardado en el carrito", "Atenci�n");
        } else {
            Messages.showMessageDialog("Ocurrio un error", "Atenci�n");
        }
    }// GEN-LAST:event_btnAgrCarritoActionPerformed

    private boolean correctFormat(String id) {
        for (int i = 0; i < id.length(); i++) {
            if (!Character.isDigit(id.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrCarrito;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        this.products = openMarketFacadeService.findAvailableProducts();
        fillTable(products);
    }
}
