/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.service.OpenMarketFacadeService;
import co.unicauca.openmarket.client.infra.Messages;
import co.unicauca.openmarket.client.infra.SessionManager;
import co.unicauca.openmarket.commons.domain.Order;
import co.unicauca.openmarket.commons.domain.User;
import co.unicauca.openmarket.observer.obs.Observador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author restr
 */
public class pnlPuntuarOrden extends javax.swing.JPanel implements Observador {

    /**
     * Creates new form pnlComprador
     */
    List<Order> listOrders;
    private OpenMarketFacadeService OpenMarketFacadeService;

    public pnlPuntuarOrden(OpenMarketFacadeService OpenMarketFacadeService) {
        initComponents();
        initializeTable();
        this.OpenMarketFacadeService = OpenMarketFacadeService;

        User usr = SessionManager.getInstance().getUser();
        if (usr != null) {
            if (!usr.getUserName().equals("Anonimo")) {
                this.listOrders = OpenMarketFacadeService.getOrders();
                fillTable(listOrders);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrdenes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jcbPuntuar = new javax.swing.JComboBox<>();
        btnPuntuarOrden = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 515));

        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOrdenes);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        jcbPuntuar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel1.add(jcbPuntuar);

        btnPuntuarOrden.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPuntuarOrden.setText("Puntuar");
        btnPuntuarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntuarOrdenActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuntuarOrden);

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        fillTable(OpenMarketFacadeService.getOrders());
        this.listOrders = OpenMarketFacadeService.getOrders();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnPuntuarOrdenActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPuntuarOrdenActionPerformed
        int selectedIndex = tblOrdenes.getSelectedRow();
        
        if (selectedIndex < 0) {
            Messages.showMessageDialog("Seleccione una orden de la tabla", "Atenci�n");
            return;
        }
        
        Order order = listOrders.get(selectedIndex);
        OpenMarketFacadeService.qualificateOrder(order, Long.parseLong(jcbPuntuar.getSelectedItem().toString()));
        Messages.showMessageDialog("Orden calificada", "Atenci�n");
    }// GEN-LAST:event_btnPuntuarOrdenActionPerformed

    private void initializeTable() {
        tblOrdenes.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "ID", "Estatus", "Precio", "Fecha", "Puntuacion"
                }));
    }

    private void fillTable(List<Order> listOrders) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblOrdenes.getModel();

        Object rowData[] = new Object[5];// No columnas
        for (int i = 0; i < listOrders.size(); i++) {
            rowData[0] = listOrders.get(i).getId();
            rowData[1] = listOrders.get(i).getStatus().getName();
            rowData[2] = listOrders.get(i).getPrice();
            rowData[3] = listOrders.get(i).getDate();
            rowData[4] = listOrders.get(i).getQualification();

            model.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPuntuarOrden;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbPuntuar;
    private javax.swing.JTable tblOrdenes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        this.listOrders = OpenMarketFacadeService.getOrders();
        fillTable(listOrders);
    }

}
