/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.unicauca.openmarket.client.presentation;

import co.unicauca.openmarket.client.domain.service.OpenMarketFacadeService;
import co.unicauca.openmarket.client.infra.Messages;
import co.unicauca.openmarket.commons.domain.Delivery;
import co.unicauca.openmarket.commons.domain.Order;
import co.unicauca.openmarket.observer.obs.Observador;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author restr
 */
public class pnlRegistrarEntrega extends javax.swing.JPanel implements Observador {

    /**
     * Creates new form pnlComprador
     */
    List<Order> orders;

    private OpenMarketFacadeService openMarketFacadeService;

    public pnlRegistrarEntrega(OpenMarketFacadeService openMarketFacadeService) {
        initComponents();
        initializeTable();
        this.openMarketFacadeService = openMarketFacadeService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntregas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnCambiar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 515));

        tblEntregas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEntregas);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 5));

        btnCambiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCambiar.setText("Cambiar");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCambiar);

        btnListar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        fillTable(openMarketFacadeService.getOrders());
        this.orders = openMarketFacadeService.getOrders();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCambiarActionPerformed
        int selectedIndex = tblEntregas.getSelectedRow();
        
        if (selectedIndex < 0) {
            Messages.showMessageDialog("Seleccione una orden de la tabla", "Atenci�n");
            return;
        }
        
        Order order = orders.get(selectedIndex);
        openMarketFacadeService.confirmOrder(order);
        Messages.showMessageDialog("Orden confirmada", "Atenci�n");
    }// GEN-LAST:event_btnCambiarActionPerformed

    private void initializeTable() {
        tblEntregas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "ID", "Estatus", "Precio", "Fecha"
                }));
    }

    private void fillTable(List<Order> listOrders) {
        initializeTable();
        DefaultTableModel model = (DefaultTableModel) tblEntregas.getModel();

        Object rowData[] = new Object[4];// No columnas
        for (int i = 0; i < listOrders.size(); i++) {
            rowData[0] = listOrders.get(i).getId();
            rowData[1] = listOrders.get(i).getStatus().getName();
            rowData[2] = listOrders.get(i).getPrice();
            rowData[3] = listOrders.get(i).getDate();

            model.addRow(rowData);
        }
    }

    private boolean correctFormatId(String id) {
        for (int i = 0; i < id.length(); i++) {
            if (!Character.isDigit(id.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEntregas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        this.orders = openMarketFacadeService.getOrders();
    }

}
